import parser from "vue-eslint-parser";
import path from "node:path";
import { fileURLToPath } from "node:url";
import js from "@eslint/js";
import { FlatCompat } from "@eslint/eslintrc";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const compat = new FlatCompat({
	baseDirectory: __dirname,
	recommendedConfig: js.configs.recommended,
	allConfig: js.configs.all
});

export default [{
	ignores: [
		"**/.eslintrc.cjs",
		"**/autogeneratedInterfaces.ts",
		"**/vue-shim.d.ts",
		"**/.chrome/**",
		"**/.vs/**",
		"!**/.vscode/**",
		"**/obj/**",
		"**/bin/**",
		"**/node_modules/**",
		"**/*.min.js",
		"**/*.min.js.LICENSE.txt",
		"**/wwwroot/dist/**",
		"**/wwwroot/libs/**"
	]
},
{
	files: [
		"**/*.ts",
		"**/*.vue",
		"**/*.js",
		"**/*.jsx",
		"**/*.cjs",
		"**/*.mjs",
		"**/*.tsx",
		"**/*.cts",
		"**/*.mts"
	],
}, ...compat.extends(
	"plugin:vue/base",
	"plugin:vue/vue3-essential",
	"plugin:vue/vue3-strongly-recommended",
	"plugin:vue/vue3-recommended",
	"eslint:recommended",
	"plugin:@typescript-eslint/recommended",
), {
	languageOptions: {
		parser: parser,
		ecmaVersion: 5,
		sourceType: "module",

		parserOptions: {
			parser: "@typescript-eslint/parser",
		},
	},

	rules: {
		"@typescript-eslint/no-inferrable-types": 0,
		"@typescript-eslint/no-explicit-any": 0,
		"@typescript-eslint/explicit-module-boundary-types": 0,
		"@typescript-eslint/ban-ts-comment": 0,
		"@typescript-eslint/no-empty-function": 0,
		//"@typescript-eslint/no-extra-semi": "warn",
		"@typescript-eslint/no-unused-vars": "warn",
		"vue/html-indent": ["warn", "tab"],
		"vue/html-self-closing": 0,
		"vue/max-attributes-per-line": 0,
		"vue/attributes-order": 0,
		"vue/html-closing-bracket-newline": 0,
		"vue/singleline-html-element-content-newline": 0,
		"vue/html-closing-bracket-spacing": "warn",
		"vue/attribute-hyphenation": 0,
		"vue/mustache-interpolation-spacing": "warn",
		"vue/multiline-html-element-content-newline": 0,
		"vue/no-v-html": "error",
		"vue/require-v-for-key": "error",
		"vue/no-use-v-if-with-v-for": "error",
		"vue/no-unused-vars": "warn",
		"vue/valid-v-model": "error",
		"vue/valid-v-for": "error",
		"vue/valid-v-bind": "error",
		"vue/no-textarea-mustache": "error",
		"vue/no-multi-spaces": "warn",
		"no-undef": "warn",
		"no-empty": "warn",
		"prefer-const": "warn",
		"no-extra-boolean-cast": "warn",
		"no-irregular-whitespace": "warn",
		semi: "off",
		//"@typescript-eslint/semi": ["warn"],
		quotes: "off",

		// "@typescript-eslint/quotes": ["warn", "double", {
		// 	avoidEscape: true,
		// 	allowTemplateLiterals: true,
		// }],

		"brace-style": "off",
		//"@typescript-eslint/brace-style": ["warn", "stroustrup"],
		curly: ["warn", "all"],

		"no-warning-comments": ["warn", {
			terms: ["todo"],
			location: "anywhere",
		}],

		eqeqeq: ["error", "always"],
		"no-unused-expressions": "error",
		"no-var": "warn",
		"@typescript-eslint/no-empty-interface": "warn",
		"vue/multi-word-component-names": 0,
		"prefer-rest-params": 0,
		"vue/component-definition-name-casing": ["warn", "kebab-case"],

		"no-console": ["warn", {
			allow: ["error"],
		}],

		"vue/first-attribute-linebreak": 0,

		"vue/component-tags-order": ["warn", {
			order: ["template", "style", "script"],
		}],
	},
}];